version: "3.9"

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: optiwms
      POSTGRES_USER: optiwms
      POSTGRES_PASSWORD: optiwms
    ports:
      - "5434:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  backend:
    build:
      context: ../backend
    depends_on:
      - db
    environment:
      SPRING_PROFILES_ACTIVE: docker
    ports:
      - "8080:8080"

  frontend:
    build:
      context: ../frontend
    depends_on:
      - backend
    ports:
      - "3000:3000"

volumes:
  db_data: {}


