"use client";

import React from 'react';

export default function StorageOptimizerDashboard() {
    
    const reallocations = [
        { 
            id: 1, 
            skuToMove: 'SKU-50992 (Low Demand)', 
            targetSku: 'SKU-10901 (High Demand)',
            fromZone: 'Zone A, Row 0',
            toZone: 'Zone D, Row 15',
            estimatedSavings: '4,500 LKR',
            forkliftMoves: 2,
            netBenefit: '+ 4,260 LKR'
        },
        { 
            id: 2, 
            skuToMove: 'SKU-88210 (Seasonal End)', 
            targetSku: 'SKU-20231 (Trending)',
            fromZone: 'Zone A, Row 1',
            toZone: 'Zone C, Row 10',
            estimatedSavings: '2,000 LKR',
            forkliftMoves: 2,
            netBenefit: '+ 1,760 LKR'
        }
    ];

    return (
        <div className="space-y-6">
            <div className="bg-white p-6 rounded-xl shadow-sm border border-gray-100">
                <h3 className="text-lg font-semibold text-gray-900 mb-4">Proposed Cross-SKU Reallocations</h3>
                <p className="text-sm text-gray-500 mb-6 max-w-3xl">
                    These moves are generated by analyzing the 6-month forecast CoV (Coefficient of Variation). 
                    The GA fitness function calculates the gross space value and deducts the exact forklift relocation cost 
                    (120 LKR per physical move) to ensure net operational profitability.
                </p>
                
                <div className="overflow-x-auto">
                    <table className="w-full text-left text-sm text-gray-600">
                        <thead className="bg-gray-50 text-gray-700">
                            <tr>
                                <th className="px-4 py-3 font-medium rounded-tl-lg">Item to Relocate</th>
                                <th className="px-4 py-3 font-medium">To Make Room For</th>
                                <th className="px-4 py-3 font-medium">Move Details</th>
                                <th className="px-4 py-3 font-medium">Forklift Cost</th>
                                <th className="px-4 py-3 font-medium">Net Value Added</th>
                                <th className="px-4 py-3 font-medium rounded-tr-lg">Action</th>
                            </tr>
                        </thead>
                        <tbody>
                            {reallocations.map((r) => (
                                <tr key={r.id} className="border-b border-gray-50 hover:bg-gray-50 transition-colors">
                                    <td className="px-4 py-3 font-medium text-gray-900">{r.skuToMove}</td>
                                    <td className="px-4 py-3 text-blue-600 font-medium">{r.targetSku}</td>
                                    <td className="px-4 py-3">
                                        <div className="flex flex-col text-xs">
                                            <span className="text-red-500 line-through">{r.fromZone}</span>
                                            <span className="text-green-600">→ {r.toZone}</span>
                                        </div>
                                    </td>
                                    <td className="px-4 py-3 text-red-500">-{r.forkliftMoves * 120} LKR</td>
                                    <td className="px-4 py-3 font-bold text-green-600">{r.netBenefit}</td>
                                    <td className="px-4 py-3">
                                        <button className="bg-blue-500 text-white px-3 py-1 rounded shadow-sm hover:bg-blue-600 text-xs font-semibold transition-colors">
                                            Execute Move
                                        </button>
                                    </td>
                                </tr>
                            ))}
                        </tbody>
                    </table>
                </div>
            </div>
            
            {/* Visualizer Placeholder */}
            <div className="bg-white p-6 rounded-xl shadow-sm border border-gray-100 flex items-center justify-center h-64 bg-gray-50/50">
                <div className="text-center">
                    <svg className="mx-auto h-12 w-12 text-gray-300" fill="none" viewBox="0 0 24 24" stroke="currentColor" aria-hidden="true">
                        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M19 11H5m14 0a2 2 0 012 2v6a2 2 0 01-2 2H5a2 2 0 01-2-2v-6a2 2 0 012-2m14 0V9a2 2 0 00-2-2M5 11V9a2 2 0 002-2m0 0V5a2 2 0 012-2h6a2 2 0 012 2v2M7 7h10" />
                    </svg>
                    <h3 className="mt-2 text-sm font-medium text-gray-900">3D Warehouse GA Visualizer</h3>
                    <p className="mt-1 text-sm text-gray-500">Interactive 3D view of the re-slotting paths will render here.</p>
                </div>
            </div>
        </div>
    );
}
