-- OptiWMS Database Migration
-- Version 16: Seed Materials Data from CSV
-- Industry Best Practice: Store data in database via Flyway migrations (not runtime seeders)
-- This migration loads all materials from Item code and descriptions.csv
-- Idempotent: Safe to run multiple times (ON CONFLICT handles duplicates)

-- Inserting 309 materials
INSERT INTO materials (material_code, description, material_type, storage_type, requires_pallet, created_at, updated_at)
VALUES
    ('100036', 'CAUSTIC SODA', 'raw_material', 'pallet', true, NOW(), NOW()),
    ('101054', 'CALCIUM CARBONATE ( GROUND )', 'raw_material', 'pallet', true, NOW(), NOW()),
    ('100098', 'SORBITOL', 'raw_material', 'pallet', true, NOW(), NOW()),
    ('101293', 'FLUFF UNTREATED - GOLDEN ISLES G4881', 'raw_material', 'pallet', true, NOW(), NOW()),
    ('100108', 'TALCUM POWDER', 'raw_material', 'pallet', true, NOW(), NOW()),
    ('100323', 'BC COLOGNE BULK - IMPORTED', 'raw_material', 'pallet', true, NOW(), NOW()),
    ('100094', 'SILICA 165 THICKENING', 'raw_material', 'pallet', true, NOW(), NOW()),
    ('101466', '3D BUBBLE NON-WOVEN TOP SHEET 38GSM-90MM', 'raw_material', 'pallet', true, NOW(), NOW()),
    ('101580', 'SODIUM SILICATE', 'raw_material', 'pallet', true, NOW(), NOW()),
    ('100460', 'GALAXY LES 70', 'raw_material', 'pallet', true, NOW(), NOW()),
    ('100039', 'EMAL 10 PHD  (  Galaxy 689 )', 'raw_material', 'pallet', true, NOW(), NOW()),
    ('101300', 'SOFT EDGE N/WOVEN HYD - AIR THROUGH 115m', 'raw_material', 'pallet', true, NOW(), NOW()),
    ('100714', 'COCOMIDOPROPYL BETAINE', 'raw_material', 'pallet', true, NOW(), NOW()),
    ('101308', 'PE BACK SHEET 170mm - WHITE', 'raw_material', 'pallet', true, NOW(), NOW()),
    ('100050', 'GLYCERINE', 'raw_material', 'pallet', true, NOW(), NOW()),
    ('101413', 'BULK BC FRESH FLORAL COLOGNE - IMPORTED', 'raw_material', 'pallet', true, NOW(), NOW()),
    ('100403', 'VIRGIN COCONUT OIL', 'raw_material', 'pallet', true, NOW(), NOW()),
    ('101736', 'ECOSMOOTH SATIN', 'raw_material', 'pallet', true, NOW(), NOW()),
    ('100110', 'TITANIUM DIOXIDE', 'raw_material', 'pallet', true, NOW(), NOW()),
    ('101305', 'SOFT EDGE PE - WHITE OPAQUE 115mm (Only', 'raw_material', 'pallet', true, NOW(), NOW()),
    ('101428', 'PREMIUM PE - PERFORATED 85mm TOP SHEET', 'raw_material', 'pallet', true, NOW(), NOW()),
    ('100030', 'CORN STARCH', 'raw_material', 'pallet', true, NOW(), NOW()),
    ('100904', 'HOT MELT ADHESIVE DMC 5228', 'raw_material', 'pallet', true, NOW(), NOW()),
    ('101065', 'BC LUCKY DUCKY COL - BULK', 'raw_material', 'pallet', true, NOW(), NOW()),
    ('101472', 'PRINTED PE POUCH 240mm - LIGHT PINK', 'raw_material', 'pallet', true, NOW(), NOW()),
    ('101017', 'Tinopal CBS X', 'raw_material', 'pallet', true, NOW(), NOW()),
    ('101302', 'AQL NON WOVEN WHITE 60mm - WHITE', 'raw_material', 'pallet', true, NOW(), NOW()),
    ('101398', 'IMPORTED BULK - BC COL CUDDLY BUNNY', 'raw_material', 'pallet', true, NOW(), NOW()),
    ('101389', 'IMPORTED BULK - BC FLORAL COL', 'raw_material', 'pallet', true, NOW(), NOW()),
    ('101762', 'Pink Pleats', 'raw_material', 'pallet', true, NOW(), NOW()),
    ('100006', 'ALCOHOL', 'raw_material', 'pallet', true, NOW(), NOW()),
    ('101399', 'IMPORTED BULK - BC COL ANGEL FAIRY', 'raw_material', 'pallet', true, NOW(), NOW()),
    ('101471', 'PRINTED PE POUCH 240mm - LIGHT PURPLE', 'raw_material', 'pallet', true, NOW(), NOW()),
    ('100038', 'XIAMETER (R) MEM - 1785 EMULSION', 'raw_material', 'pallet', true, NOW(), NOW()),
    ('100525', 'LUZI 187340', 'raw_material', 'pallet', true, NOW(), NOW()),
    ('101374', 'CUTINA EGDS', 'raw_material', 'pallet', true, NOW(), NOW()),
    ('101390', 'IMPORTED BULK - BC BED TIME COL', 'raw_material', 'pallet', true, NOW(), NOW()),
    ('101429', 'PREMIUM PE PERFORATED 90mm TOP SHEET', 'raw_material', 'pallet', true, NOW(), NOW()),
    ('101862', 'BULK BC HERBAL COLOGNE - IMPORTED', 'raw_material', 'pallet', true, NOW(), NOW()),
    ('100026', 'CETYL ALCOHOL', 'raw_material', 'pallet', true, NOW(), NOW()),
    ('100105', 'STEARIC ACID', 'raw_material', 'pallet', true, NOW(), NOW()),
    ('100171', 'OPTAMINT 293250', 'raw_material', 'pallet', true, NOW(), NOW()),
    ('100835', 'SANDALWOOD CO 13490T', 'raw_material', 'pallet', true, NOW(), NOW()),
    ('100913', 'SAP SA 60 N  TYPE II', 'raw_material', 'pallet', true, NOW(), NOW()),
    ('100018', 'BRIQUEST ADPA', 'raw_material', 'pallet', true, NOW(), NOW()),
    ('100043', 'EMPILAN GMS SE 40(CAFLOAN)', 'raw_material', 'pallet', true, NOW(), NOW()),
    ('100093', 'SILICON', 'raw_material', 'pallet', true, NOW(), NOW()),
    ('100097', 'S.M.F.P.', 'raw_material', 'pallet', true, NOW(), NOW()),
    ('101295', 'RELEASE PAPER WINGS 65mm - WHITE', 'raw_material', 'pallet', true, NOW(), NOW()),
    ('101468', 'NEW RL.PAPER PRNTD. CENTER 50mm - PINK', 'raw_material', 'pallet', true, NOW(), NOW()),
    ('101470', 'PRINTED PE POUCH 290mm - SEA GREEN', 'raw_material', 'pallet', true, NOW(), NOW()),
    ('101488', 'ROSE & CARE MOD 434031 ( R )', 'raw_material', 'pallet', true, NOW(), NOW()),
    ('101496', 'DHARIYAL CMC - IG 3040', 'raw_material', 'pallet', true, NOW(), NOW()),
    ('101517', 'ABBRASIVE SILICA ( ZEODENT 113 )', 'raw_material', 'pallet', true, NOW(), NOW()),
    ('101637', 'PINK PLUM IMP 4 EAE 36544/00', 'raw_material', 'pallet', true, NOW(), NOW()),
    ('100035', 'CLIMBAZOLE', 'raw_material', 'pallet', true, NOW(), NOW()),
    ('100044', 'EMANON PCSA', 'raw_material', 'pallet', true, NOW(), NOW()),
    ('100069', 'METHYL PARABEN', 'raw_material', 'pallet', true, NOW(), NOW()),
    ('100118', 'TRILON BD ( DISODIUM EDTA )', 'raw_material', 'pallet', true, NOW(), NOW()),
    ('100119', 'TRI SODIUM ORTHOPHOSPHATE', 'raw_material', 'pallet', true, NOW(), NOW()),
    ('100201', 'POLYETHELYENE GLYCOL ( PEG 1500 )', 'raw_material', 'pallet', true, NOW(), NOW()),
    ('100903', 'HOT MELT ADHESIVE DMC 5227', 'raw_material', 'pallet', true, NOW(), NOW()),
    ('101273', 'FIXATE FREE STYLE POLYMER', 'raw_material', 'pallet', true, NOW(), NOW()),
    ('101409', 'CITRUS SKY ( SRILEX 1886 )', 'raw_material', 'pallet', true, NOW(), NOW()),
    ('101463', 'TRIPOTASSIUM CITRATE G 2040', 'raw_material', 'pallet', true, NOW(), NOW()),
    ('101467', 'NEW RL.PAPER PRNTD. CENTER 50mm - PURPLE', 'raw_material', 'pallet', true, NOW(), NOW()),
    ('101489', 'FLOWER POWER MOD 434033 (J)', 'raw_material', 'pallet', true, NOW(), NOW()),
    ('101623', 'SUNFLOWER SMILE 1MP 2', 'raw_material', 'pallet', true, NOW(), NOW()),
    ('101625', 'WINDING PATH', 'raw_material', 'pallet', true, NOW(), NOW()),
    ('101763', 'LUXURY CREME', 'raw_material', 'pallet', true, NOW(), NOW()),
    ('101859', 'BULK GOLD BLACK JEANS - IMPORTED', 'raw_material', 'pallet', true, NOW(), NOW()),
    ('100010', 'ALLANTOIN B.P', 'raw_material', 'pallet', true, NOW(), NOW()),
    ('100080', 'PROTACHEM SMS', 'raw_material', 'pallet', true, NOW(), NOW()),
    ('100099', 'SODIUM BENZOATE', 'raw_material', 'pallet', true, NOW(), NOW()),
    ('100100', 'SODIUM SACHCHARIN', 'raw_material', 'pallet', true, NOW(), NOW()),
    ('100198', 'LANELGINE', 'raw_material', 'pallet', true, NOW(), NOW()),
    ('100713', 'MAGNESIUM SULPHATE', 'raw_material', 'pallet', true, NOW(), NOW()),
    ('101015', 'UVTEX POWDER (Optical brightener)', 'raw_material', 'pallet', true, NOW(), NOW()),
    ('101091', 'BENZYL ALCOHOL', 'raw_material', 'pallet', true, NOW(), NOW()),
    ('101282', 'POLYOX WSR 301', 'raw_material', 'pallet', true, NOW(), NOW()),
    ('101298', 'POUCH TAPE 30mm', 'raw_material', 'pallet', true, NOW(), NOW()),
    ('101370', 'CLASSIC FRESH 3 ( SRILEX 1879 )', 'raw_material', 'pallet', true, NOW(), NOW()),
    ('101376', 'RITA IPM ( ISOPROPYL MIRISTATE NF )', 'raw_material', 'pallet', true, NOW(), NOW()),
    ('101380', 'COVABSORB DS', 'raw_material', 'pallet', true, NOW(), NOW()),
    ('101453', 'SPRING ORCHID PSX11978 AW', 'raw_material', 'pallet', true, NOW(), NOW()),
    ('101469', 'NEW RELEASE PAPER PRINTED 50mm - GREEN', 'raw_material', 'pallet', true, NOW(), NOW()),
    ('101515', 'SHANDONG CMC', 'raw_material', 'pallet', true, NOW(), NOW()),
    ('101605', 'SRILEX 1904', 'raw_material', 'pallet', true, NOW(), NOW()),
    ('101825', 'SWEET ALMOND OIL', 'raw_material', 'pallet', true, NOW(), NOW()),
    ('101832', 'CARBOMER 980', 'raw_material', 'pallet', true, NOW(), NOW()),
    ('101841', 'JAGUAR C 13 S', 'raw_material', 'pallet', true, NOW(), NOW()),
    ('100448', 'PARIS 009 (  Srilex 1718 )', 'raw_material', 'pallet', true, NOW(), NOW()),
    ('100005', 'ETHYL ALCOHOL ( Undenatured )', 'raw_material', 'pallet', true, NOW(), NOW()),
    ('100012', 'AMPHISOL', 'raw_material', 'pallet', true, NOW(), NOW()),
    ('100016', 'F.D.& C BLUE 1', 'raw_material', 'pallet', true, NOW(), NOW()),
    ('100019', 'BHT', 'raw_material', 'pallet', true, NOW(), NOW()),
    ('100028', 'CITRIC ACID', 'raw_material', 'pallet', true, NOW(), NOW()),
    ('100031', 'COPPER CHLOROPHYLL LIQUID', 'raw_material', 'pallet', true, NOW(), NOW()),
    ('100033', 'CREMOPHOR RH 40', 'raw_material', 'pallet', true, NOW(), NOW()),
    ('100046', 'FRESCOLAT ML', 'raw_material', 'pallet', true, NOW(), NOW()),
    ('100066', 'MENTHOL', 'raw_material', 'pallet', true, NOW(), NOW()),
    ('100071', 'MULSIFAN RT', 'raw_material', 'pallet', true, NOW(), NOW()),
    ('100072', 'MICROCRYSTALLINE WAX', 'raw_material', 'pallet', true, NOW(), NOW()),
    ('100078', 'POTASSIUM HYDROXIDE', 'raw_material', 'pallet', true, NOW(), NOW()),
    ('100084', 'PROPYL PARABEN', 'raw_material', 'pallet', true, NOW(), NOW()),
    ('100085', 'F.D.& C RED NO 04', 'raw_material', 'pallet', true, NOW(), NOW()),
    ('100086', 'F D & C RED NO 33', 'raw_material', 'pallet', true, NOW(), NOW()),
    ('100090', 'SALCARE 91', 'raw_material', 'pallet', true, NOW(), NOW()),
    ('100109', 'TRI ETHANOL AMINE', 'raw_material', 'pallet', true, NOW(), NOW()),
    ('100117', 'THIMOL', 'raw_material', 'pallet', true, NOW(), NOW()),
    ('100120', 'TWEEN 20', 'raw_material', 'pallet', true, NOW(), NOW()),
    ('100125', 'LAVANYA ZUNI DISPERSION', 'raw_material', 'pallet', true, NOW(), NOW()),
    ('100127', 'PURI COLOR YELLOW PYE 1-L', 'raw_material', 'pallet', true, NOW(), NOW()),
    ('100128', 'VITAMINE E', 'raw_material', 'pallet', true, NOW(), NOW()),
    ('100130', 'WHITE BEES WAX', 'raw_material', 'pallet', true, NOW(), NOW()),
    ('100132', 'F.D.& C YELLOW 5', 'raw_material', 'pallet', true, NOW(), NOW()),
    ('100134', 'ZINC OXIDE', 'raw_material', 'pallet', true, NOW(), NOW()),
    ('100140', 'CAN CAN', 'raw_material', 'pallet', true, NOW(), NOW()),
    ('100143', 'CIEN 85318', 'raw_material', 'pallet', true, NOW(), NOW()),
    ('100147', 'ETERNAL ESS.OIL', 'raw_material', 'pallet', true, NOW(), NOW()),
    ('100149', 'GIVEX 18763', 'raw_material', 'pallet', true, NOW(), NOW()),
    ('100151', 'GIVEX 22324', 'raw_material', 'pallet', true, NOW(), NOW()),
    ('100152', 'GIVEX 23541', 'raw_material', 'pallet', true, NOW(), NOW()),
    ('100158', 'JASMINE ESS.OIL', 'raw_material', 'pallet', true, NOW(), NOW()),
    ('100160', 'JF G 1039042', 'raw_material', 'pallet', true, NOW(), NOW()),
    ('100162', 'LABRADOR 175504', 'raw_material', 'pallet', true, NOW(), NOW()),
    ('100165', 'LITTLE JOHN', 'raw_material', 'pallet', true, NOW(), NOW()),
    ('100178', 'RAINBOW D', 'raw_material', 'pallet', true, NOW(), NOW()),
    ('100183', 'SANDLE WOOD CO 13490B', 'raw_material', 'pallet', true, NOW(), NOW()),
    ('100202', 'PARC F', 'raw_material', 'pallet', true, NOW(), NOW()),
    ('100304', 'SAVENDRA ROOTS', 'raw_material', 'pallet', true, NOW(), NOW()),
    ('100346', 'WHITE SANDLEWOOD', 'raw_material', 'pallet', true, NOW(), NOW()),
    ('101581', 'NEO HELIOPAN BB', 'raw_material', 'pallet', true, NOW(), NOW()),
    ('100473', 'GALAXY 111', 'raw_material', 'pallet', true, NOW(), NOW()),
    ('100483', 'CETRIMIDE B.P', 'raw_material', 'pallet', true, NOW(), NOW()),
    ('100503', 'BLACK NIGHT 290686', 'raw_material', 'pallet', true, NOW(), NOW()),
    ('100527', 'CARBOPOL AQUA SF - 1', 'raw_material', 'pallet', true, NOW(), NOW()),
    ('100535', 'GY COL BULK - IMPORTED (  LOVE AFFAIR  )', 'raw_material', 'pallet', true, NOW(), NOW()),
    ('100536', 'GY COL BULK - IMPTED ( MISCHIEF MAKER  )', 'raw_material', 'pallet', true, NOW(), NOW()),
    ('100537', 'GY COL BULK - IMPORTED ( SECRET CRUSH )', 'raw_material', 'pallet', true, NOW(), NOW()),
    ('100594', 'SOMERSET CARE 30 CR (  Srilex 1730  )', 'raw_material', 'pallet', true, NOW(), NOW()),
    ('100840', 'MALE INSTINCT', 'raw_material', 'pallet', true, NOW(), NOW()),
    ('101582', 'LAURIC ACID', 'raw_material', 'pallet', true, NOW(), NOW()),
    ('100873', 'MONO PROPOLYNE GLYCOL', 'raw_material', 'pallet', true, NOW(), NOW()),
    ('100874', 'KINGSTON IND 694592', 'raw_material', 'pallet', true, NOW(), NOW()),
    ('100894', 'SRILEX 1798', 'raw_material', 'pallet', true, NOW(), NOW()),
    ('100986', 'OPTAMINT FSM 380616', 'raw_material', 'pallet', true, NOW(), NOW()),
    ('101016', 'INDUCOS 14/3 BLUE', 'raw_material', 'pallet', true, NOW(), NOW()),
    ('101028', 'Srilex 1815', 'raw_material', 'pallet', true, NOW(), NOW()),
    ('101043', 'AJIDEW NL - 50', 'raw_material', 'pallet', true, NOW(), NOW()),
    ('101073', 'FABRICA 362781', 'raw_material', 'pallet', true, NOW(), NOW()),
    ('101083', 'CMC POLYMER', 'raw_material', 'pallet', true, NOW(), NOW()),
    ('101085', 'TINOPAL DMA - X', 'raw_material', 'pallet', true, NOW(), NOW()),
    ('101163', 'GERMALL 115', 'raw_material', 'pallet', true, NOW(), NOW()),
    ('101203', 'ULTREZ 20', 'raw_material', 'pallet', true, NOW(), NOW()),
    ('101204', 'OLIVAM 1000', 'raw_material', 'pallet', true, NOW(), NOW()),
    ('101207', 'PETROLAN, ULTRA WHITE, USP', 'raw_material', 'pallet', true, NOW(), NOW()),
    ('101208', 'SHEBU - WS', 'raw_material', 'pallet', true, NOW(), NOW()),
    ('101211', 'L-ARGININE', 'raw_material', 'pallet', true, NOW(), NOW()),
    ('101216', 'UVINUL MC 80', 'raw_material', 'pallet', true, NOW(), NOW()),
    ('101223', 'INNOVATION AR 285118', 'raw_material', 'pallet', true, NOW(), NOW()),
    ('101234', 'UNILACTAMIN L-17', 'raw_material', 'pallet', true, NOW(), NOW()),
    ('101235', 'METHOCEL 40 - 0202', 'raw_material', 'pallet', true, NOW(), NOW()),
    ('101264', 'DOW CORNING 244', 'raw_material', 'pallet', true, NOW(), NOW()),
    ('101265', 'ROSE WATER', 'raw_material', 'pallet', true, NOW(), NOW()),
    ('101267', 'WATER LILLY', 'raw_material', 'pallet', true, NOW(), NOW()),
    ('101271', 'COSMENYL GREEN GG ( C.I. NO:P.G.7 )', 'raw_material', 'pallet', true, NOW(), NOW()),
    ('101274', 'ULTREZ 21', 'raw_material', 'pallet', true, NOW(), NOW()),
    ('101275', 'HYDROLYZED WHEAT PROTEIN', 'raw_material', 'pallet', true, NOW(), NOW()),
    ('101276', 'BEN # 4', 'raw_material', 'pallet', true, NOW(), NOW()),
    ('101277', 'AMP No:  95', 'raw_material', 'pallet', true, NOW(), NOW()),
    ('101278', 'FIELD OF DAISIES 956773', 'raw_material', 'pallet', true, NOW(), NOW()),
    ('101279', 'XAVIER 488490', 'raw_material', 'pallet', true, NOW(), NOW()),
    ('101280', 'FRENCH APPLE 884412', 'raw_material', 'pallet', true, NOW(), NOW()),
    ('101281', 'NOVETHIX L -  10', 'raw_material', 'pallet', true, NOW(), NOW()),
    ('101283', 'GLUCOPON 600 CSUP', 'raw_material', 'pallet', true, NOW(), NOW()),
    ('101285', 'RHEOVIS AT 120', 'raw_material', 'pallet', true, NOW(), NOW()),
    ('101286', 'COSMENYL VIOLET RL', 'raw_material', 'pallet', true, NOW(), NOW()),
    ('101287', 'UCON LB 1145', 'raw_material', 'pallet', true, NOW(), NOW()),
    ('101288', 'ACUSOL OP 301', 'raw_material', 'pallet', true, NOW(), NOW()),
    ('101299', 'SOFT EDGE N/WOVEN HYD - AIR THROUGH 60mm', 'raw_material', 'pallet', true, NOW(), NOW()),
    ('101304', 'SOFT EDGE PE - WHITE OPAQUE 60mm', 'raw_material', 'pallet', true, NOW(), NOW()),
    ('101307', 'PE BACK SHEET 120mm - WHITE', 'raw_material', 'pallet', true, NOW(), NOW()),
    ('101345', 'RL. PAPER PRNTD CENTRE 50mm - LIGHT BLUE', 'raw_material', 'pallet', true, NOW(), NOW()),
    ('101346', 'PE POUCH 240mm - LIGHT BLUE', 'raw_material', 'pallet', true, NOW(), NOW()),
    ('101359', 'POUCH TAPE 30mm - LIGHT GREEN', 'raw_material', 'pallet', true, NOW(), NOW()),
    ('101363', 'BABY HERBAL COLOGNE SV 46167 C', 'raw_material', 'pallet', true, NOW(), NOW()),
    ('101364', 'CORAL GABLES MOOD SH ( SRILEX 1875 )', 'raw_material', 'pallet', true, NOW(), NOW()),
    ('101365', 'CORAL GABLES MOOD LO ( SRILEX 1876 )', 'raw_material', 'pallet', true, NOW(), NOW()),
    ('101366', 'SRILEX 1722 IMP - 1 ( SRILEX 1880 )', 'raw_material', 'pallet', true, NOW(), NOW()),
    ('101369', 'ORANGE SAI  X2L0232', 'raw_material', 'pallet', true, NOW(), NOW()),
    ('101373', 'ALMOND SEED', 'raw_material', 'pallet', true, NOW(), NOW()),
    ('101375', 'POMACE OLIVE OIL', 'raw_material', 'pallet', true, NOW(), NOW()),
    ('101377', 'TINOSAN HP 100', 'raw_material', 'pallet', true, NOW(), NOW()),
    ('101378', 'LUTENSOL TO 8', 'raw_material', 'pallet', true, NOW(), NOW()),
    ('101379', 'ACUSOL 445 N', 'raw_material', 'pallet', true, NOW(), NOW()),
    ('101382', 'CREME SILK 744193', 'raw_material', 'pallet', true, NOW(), NOW()),
    ('101394', 'TAPIOCA PURE STARCH', 'raw_material', 'pallet', true, NOW(), NOW()),
    ('101396', 'S / WOOD CHIPS', 'raw_material', 'pallet', true, NOW(), NOW()),
    ('101397', 'TENDER SPLASH SUPER 755469', 'raw_material', 'pallet', true, NOW(), NOW()),
    ('101401', 'HAIR FALL PROTECTION TSG15-06236', 'raw_material', 'pallet', true, NOW(), NOW()),
    ('101402', 'KERASOL', 'raw_material', 'pallet', true, NOW(), NOW()),
    ('101405', 'SILVER LUSTRE STAB 2 ( SRILEX 1882 )', 'raw_material', 'pallet', true, NOW(), NOW()),
    ('101406', 'WHOLE EGG POWDER', 'raw_material', 'pallet', true, NOW(), NOW()),
    ('101407', 'SILVER LUSTRE INDE (SRILEX 1883)', 'raw_material', 'pallet', true, NOW(), NOW()),
    ('101410', 'CITRUS TIDES IMP ( SRILEX 1888 )', 'raw_material', 'pallet', true, NOW(), NOW()),
    ('101411', 'FLORAL HEAVEN IMP ( SRILEX 1887 )', 'raw_material', 'pallet', true, NOW(), NOW()),
    ('101415', 'SODIUM HYDROXIDE', 'raw_material', 'pallet', true, NOW(), NOW()),
    ('101416', 'PEA NUT EXTRACT (BIOTIN)', 'raw_material', 'pallet', true, NOW(), NOW()),
    ('101443', 'VETIVER OIL', 'raw_material', 'pallet', true, NOW(), NOW()),
    ('101474', 'PS GOLD GEL AM 47259 C', 'raw_material', 'pallet', true, NOW(), NOW()),
    ('101483', 'HIMALAYAN ESSENCE IMP IND', 'raw_material', 'pallet', true, NOW(), NOW()),
    ('101493', 'LAVANYA REVOLUTUM DISPERSION', 'raw_material', 'pallet', true, NOW(), NOW()),
    ('101499', 'SODIUM FLUORIDE', 'raw_material', 'pallet', true, NOW(), NOW()),
    ('101500', 'PHENOXY ETHANOL', 'raw_material', 'pallet', true, NOW(), NOW()),
    ('101503', 'KOH', 'raw_material', 'pallet', true, NOW(), NOW()),
    ('101505', 'MYRISTIC ACID', 'raw_material', 'pallet', true, NOW(), NOW()),
    ('101516', 'ZINC ACETATE', 'raw_material', 'pallet', true, NOW(), NOW()),
    ('101534', 'LAVANYA DECORUM DISPERSION', 'raw_material', 'pallet', true, NOW(), NOW()),
    ('101565', 'OPTAMINT 724636', 'raw_material', 'pallet', true, NOW(), NOW()),
    ('101566', 'OPTAMINT 725013', 'raw_material', 'pallet', true, NOW(), NOW()),
    ('101567', 'OPTAMINT 725024', 'raw_material', 'pallet', true, NOW(), NOW()),
    ('101574', 'POTASSIUM SORBATE', 'raw_material', 'pallet', true, NOW(), NOW()),
    ('101575', 'GLYCINE', 'raw_material', 'pallet', true, NOW(), NOW()),
    ('101576', 'OPTAMINT 701655', 'raw_material', 'pallet', true, NOW(), NOW()),
    ('101577', 'GREEN BLOSSOM', 'raw_material', 'pallet', true, NOW(), NOW()),
    ('101583', 'LEMON RUSH H', 'raw_material', 'pallet', true, NOW(), NOW()),
    ('101584', 'VIRGIN KING COCONUT OIL', 'raw_material', 'pallet', true, NOW(), NOW()),
    ('101593', 'SENSIDIN DO', 'raw_material', 'pallet', true, NOW(), NOW()),
    ('101594', 'OPTAMINT 727877', 'raw_material', 'pallet', true, NOW(), NOW()),
    ('101595', 'OPTAMINT 728948', 'raw_material', 'pallet', true, NOW(), NOW()),
    ('101597', 'ZINC SULPHATE HEPTA HYDRATE', 'raw_material', 'pallet', true, NOW(), NOW()),
    ('101603', 'SILICA GRANULES - BIGGER SIZE (BLUE)', 'raw_material', 'pallet', true, NOW(), NOW()),
    ('101604', 'SILICA GRANULES - BIGGER SIZE (GREEN)', 'raw_material', 'pallet', true, NOW(), NOW()),
    ('101613', 'SODIUM CHLORIDE - EXTRA PURE 99.5%', 'raw_material', 'pallet', true, NOW(), NOW()),
    ('101615', 'GILOU FREEZE AM 40835 B', 'raw_material', 'pallet', true, NOW(), NOW()),
    ('101617', 'TRUE XTREM VIKING AM 53357', 'raw_material', 'pallet', true, NOW(), NOW()),
    ('101653', 'BEE''S HONEY EXTRACT', 'raw_material', 'pallet', true, NOW(), NOW()),
    ('101697', 'NIACINAMIDE', 'raw_material', 'pallet', true, NOW(), NOW()),
    ('101698', 'NOVEMER EC 2', 'raw_material', 'pallet', true, NOW(), NOW()),
    ('101699', 'VISCOFIL WHITE ARCL 30', 'raw_material', 'pallet', true, NOW(), NOW()),
    ('101700', 'CC OXIDE YELLOW FP 401', 'raw_material', 'pallet', true, NOW(), NOW()),
    ('101701', 'Dill Seeds', 'raw_material', 'pallet', true, NOW(), NOW()),
    ('101702', 'UNIPEARL SYE', 'raw_material', 'pallet', true, NOW(), NOW()),
    ('101733', 'BELCILEG 2', 'raw_material', 'pallet', true, NOW(), NOW()),
    ('101734', 'AVOCADO BUTTER', 'raw_material', 'pallet', true, NOW(), NOW()),
    ('101735', 'MICONOL CM', 'raw_material', 'pallet', true, NOW(), NOW()),
    ('101737', 'GREEN VIBRAT 2', 'raw_material', 'pallet', true, NOW(), NOW()),
    ('101738', 'CHEM 1789 -BUTYLMETHOXYDIBENZOYL METHANE', 'raw_material', 'pallet', true, NOW(), NOW()),
    ('101739', 'SAFFRON', 'raw_material', 'pallet', true, NOW(), NOW()),
    ('101740', 'LAVENDER OIL', 'raw_material', 'pallet', true, NOW(), NOW()),
    ('101742', 'PINK PETAL TOUCH - FRAGRANCE', 'raw_material', 'pallet', true, NOW(), NOW()),
    ('101760', 'GREEN PASTURES (Srilex 1915)', 'raw_material', 'pallet', true, NOW(), NOW()),
    ('101766', 'GOLDEN GLOW', 'raw_material', 'pallet', true, NOW(), NOW()),
    ('101768', 'ELEGANT WHITE', 'raw_material', 'pallet', true, NOW(), NOW()),
    ('101783', 'MYSTIC PURPLE', 'raw_material', 'pallet', true, NOW(), NOW()),
    ('101784', 'Lavender HS', 'raw_material', 'pallet', true, NOW(), NOW()),
    ('101785', 'Waterlily Mist', 'raw_material', 'pallet', true, NOW(), NOW()),
    ('101786', 'HYDRA NOURISHING', 'raw_material', 'pallet', true, NOW(), NOW()),
    ('101793', 'FLEXONYL YELLOW G 30', 'raw_material', 'pallet', true, NOW(), NOW()),
    ('101794', 'REDENSYL', 'raw_material', 'pallet', true, NOW(), NOW()),
    ('101796', 'Sera Sense RB 21', 'raw_material', 'pallet', true, NOW(), NOW()),
    ('101797', 'Sera Sense SF CM 5(Cyclopentasiloxane)', 'raw_material', 'pallet', true, NOW(), NOW()),
    ('101798', 'Sera Sense GB 10 ( Gum Blend)', 'raw_material', 'pallet', true, NOW(), NOW()),
    ('101799', 'Sera Sense SF PTM (Phenyl Trimethicone)', 'raw_material', 'pallet', true, NOW(), NOW()),
    ('101800', 'Sera Sense SF CM 56(Cyclopenta and Hexasiloxane)', 'raw_material', 'pallet', true, NOW(), NOW()),
    ('101806', 'Grape Seed Oil', 'raw_material', 'pallet', true, NOW(), NOW()),
    ('101807', 'D & C Violet 2 colour powder', 'raw_material', 'pallet', true, NOW(), NOW()),
    ('101812', 'Jojoba Oil', 'raw_material', 'pallet', true, NOW(), NOW()),
    ('101814', 'Argan Oil', 'raw_material', 'pallet', true, NOW(), NOW()),
    ('101819', 'Pomegranate Oil', 'raw_material', 'pallet', true, NOW(), NOW()),
    ('101821', 'ELO HAIR OIL TK 59073B', 'raw_material', 'pallet', true, NOW(), NOW()),
    ('101822', 'Elo Orchid TK 59073', 'raw_material', 'pallet', true, NOW(), NOW()),
    ('101823', 'Rosemary Oil', 'raw_material', 'pallet', true, NOW(), NOW()),
    ('101824', 'AVACADO OIL', 'raw_material', 'pallet', true, NOW(), NOW()),
    ('101826', 'ORANGE OIL', 'raw_material', 'pallet', true, NOW(), NOW()),
    ('101827', 'BLACK SEED OIL', 'raw_material', 'pallet', true, NOW(), NOW()),
    ('101828', 'CAMOMILE OIL', 'raw_material', 'pallet', true, NOW(), NOW()),
    ('101830', 'ALMOND & VITAMIN C EXTRACT', 'raw_material', 'pallet', true, NOW(), NOW()),
    ('101831', 'GLAMOUR CURLS 763789 (FRAGRANCE)', 'raw_material', 'pallet', true, NOW(), NOW()),
    ('101833', 'GREEN BEAUTY (FRAGRANCE)', 'raw_material', 'pallet', true, NOW(), NOW()),
    ('101835', 'BLACK IMPACT T 15017012 (FRAGRANCE)', 'raw_material', 'pallet', true, NOW(), NOW()),
    ('101836', 'GINOL 1618 TA (CETO-STEARYL ALCOHOL)', 'raw_material', 'pallet', true, NOW(), NOW()),
    ('101838', 'UCON LUBRICANT 50 - HB - 660', 'raw_material', 'pallet', true, NOW(), NOW()),
    ('101839', 'GENAMIN KDMP', 'raw_material', 'pallet', true, NOW(), NOW()),
    ('101840', 'BELSIL ADM 331', 'raw_material', 'pallet', true, NOW(), NOW()),
    ('101842', 'SCHERCODINE (TM) S AMIDO AMINE', 'raw_material', 'pallet', true, NOW(), NOW()),
    ('101525', 'LUBRAJEL OIL', 'raw_material', 'pallet', true, NOW(), NOW()),
    ('101383', 'CAMPHOR', 'raw_material', 'pallet', true, NOW(), NOW()),
    ('101384', 'EUCALYPTAS OIL', 'raw_material', 'pallet', true, NOW(), NOW()),
    ('101385', 'METHYL SALICYLATE', 'raw_material', 'pallet', true, NOW(), NOW()),
    ('101753', 'PE POUCH 240mm - NEW BLUE COLOR(SAMPLE2)', 'raw_material', 'pallet', true, NOW(), NOW()),
    ('101758', 'RL. PAPER PRNTD CENTRE 50mm - BLUE COLOR', 'raw_material', 'pallet', true, NOW(), NOW()),
    ('101808', 'Macadamia Oil', 'raw_material', 'pallet', true, NOW(), NOW()),
    ('101810', 'Camellia Oil', 'raw_material', 'pallet', true, NOW(), NOW()),
    ('101811', 'Hibiscus Oil', 'raw_material', 'pallet', true, NOW(), NOW()),
    ('100096', 'SALISILC ACID', 'raw_material', 'pallet', true, NOW(), NOW()),
    ('101284', 'ECOSENSE 919', 'raw_material', 'pallet', true, NOW(), NOW()),
    ('101504', 'AQUA SF - 2', 'raw_material', 'pallet', true, NOW(), NOW()),
    ('101506', 'FRESH SCRUB', 'raw_material', 'pallet', true, NOW(), NOW()),
    ('101507', 'UNIPEARL', 'raw_material', 'pallet', true, NOW(), NOW()),
    ('101508', 'TINGLING FRESH', 'raw_material', 'pallet', true, NOW(), NOW()),
    ('101755', 'RL. PAPER PRNTD CENTRE 50mm - PINK COLOR', 'raw_material', 'pallet', true, NOW(), NOW()),
    ('101756', 'PE POUCH 290mm - LIGHT PINK', 'raw_material', 'pallet', true, NOW(), NOW()),
    ('101804', 'Geranium Oil', 'raw_material', 'pallet', true, NOW(), NOW()),
    ('101813', 'Sesame Oil', 'raw_material', 'pallet', true, NOW(), NOW()),
    ('101816', 'Walnut Oil', 'raw_material', 'pallet', true, NOW(), NOW()),
    ('101818', 'LAVENDER OIL', 'raw_material', 'pallet', true, NOW(), NOW()),
    ('101820', 'Brahmi Oil', 'raw_material', 'pallet', true, NOW(), NOW())
ON CONFLICT (material_code) DO UPDATE 
SET description = EXCLUDED.description, updated_at = NOW();

-- Update materials that don't require pallets (from Raw matrilas not store in pallets.csv)
UPDATE materials SET requires_pallet = false, storage_type = 'bulk' 
WHERE material_code IN (
    '100133',
    '100199',
    '100756',
    '100764',
    '100946',
    '100947',
    '100948',
    '101004',
    '101084',
    '101853',
    '100200'
);

