ALTER TABLE order_items
    ADD COLUMN IF NOT EXISTS weight_kg DECIMAL(10,2),
    ADD COLUMN IF NOT EXISTS height_cm DECIMAL(10,2),
    ADD COLUMN IF NOT EXISTS length_cm DECIMAL(10,2),
    ADD COLUMN IF NOT EXISTS width_cm DECIMAL(10,2);