import { apiClient } from './client';

export interface Location {
  id: string;
  warehouseId: string;
  locationCode: string;
  area?: string;
  rowNumber?: string;
  bayNumber?: string;
  levelNumber?: number;
  binPosition?: string;
  locationType?: string;
  zoneType?: string; // STORAGE, STAGING, RECEIVING, SHIPMENT, PACKING
  capacity?: number;
  isActive: boolean;
  qrCode?: string;
  createdAt?: string;
  // Rack system fields
  rackStatus?: string;
  amalgamatedClass?: string;
  description?: string;
  notes?: string;
  accessibilityRating?: number;
  coordinateX?: number;
  coordinateY?: number;
  maxPalletCapacity?: number;
  currentPalletCount?: number;
  maxWeightKg?: number;
  maxVolumeCm3?: number;
  maxLpnCount?: number;
}

export interface CreateLocationRequest {
  warehouseId: string;
  locationCode: string;
  area?: string;
  rowNumber?: string;
  bayNumber?: string;
  levelNumber?: number;
  binPosition?: string;
  locationType?: string;
  capacity?: number;
  isActive?: boolean;
}

export interface UpdateLocationRequest {
  area?: string;
  rowNumber?: string;
  bayNumber?: string;
  levelNumber?: number;
  binPosition?: string;
  locationType?: string;
  capacity?: number;
  isActive?: boolean;
  rackStatus?: string;
  amalgamatedClass?: string;
  description?: string;
  notes?: string;
  accessibilityRating?: number;
  coordinateX?: number;
  coordinateY?: number;
  maxPalletCapacity?: number;
  currentPalletCount?: number;
  maxWeightKg?: number;
  maxVolumeCm3?: number;
  maxLpnCount?: number;
}

export interface BinOccupancy {
  locationId: string;
  locationCode: string;
  rackId: string;
  area?: string;
  rowNumber?: string;
  bayNumber?: string;
  levelNumber?: number;
  binPosition?: string;
  quantity: number;
  materialCode?: string | null;
  unitsPerPallet?: number | null;
  palletCount: number;
  binWeightKg?: number | null;
  palletWeightKg?: number | null;
  maxPalletCapacity: number;
  maxWeightKg?: number | null;
  levelWeightCapacityKg?: number | null;
  levelWeightUsedKg?: number | null;
  levelPalletCapacity?: number | null;
}

export interface RackSummary {
  rackId: string;
  area?: string;
  rowNumber?: string;
  bayNumber?: string;
  representativeLocationId?: string | null;
  representativeLocationCode?: string | null;
  locationType?: string | null;
  rackStatus?: string | null;
  amalgamatedClass?: string | null;
  description?: string | null;
  coordinateX?: number | null;
  coordinateY?: number | null;
  binCount: number;
  maxLevels: number;
  positionsPerLevel: number;
  occupiedBins: number;
  totalQuantity: number;
  palletCount: number;
  totalWeightKg: number;
  palletCapacity: number;
  weightCapacityKg: number;
  autoGenerated: boolean;
}

export interface OperationalStation {
  locationCode: string;
  locationType?: string | null;
  zoneType: string;
  coordinateX: number;
  coordinateY: number;
}

export interface IntegritySummary {
  totalMaterials: number;
  defaultsAssigned: number;
  materialsWithoutDefault: number;
  inventoryRows: number;
  inventoryQtySum: number;
  inventoryRowsNullLocation: number;
  wrongTypeNonBulkInBulk: number;
  wrongTypeBulkInNonBulk: number;
  defaultsToInactiveOrBlocked: number;
  duplicatePrimaryLocationCount: number;
  lowLike: number;
  availableLike: number;
}

export interface PlacementLine {
  locationCode: string;
  palletCount: number;
  quantityAllocated: number;
  rackId?: string | null;
  levelNumber?: number | null;
}

export interface PlacementPlan {
  requiredPallets: number;
  assignedPallets: number;
  remainingPallets: number;
  lines: PlacementLine[];
  notes: string[];
}

export interface UpdateRackRequest {
  rackStatus?: string;
  amalgamatedClass?: string;
  description?: string;
  notes?: string;
  accessibilityRating?: number;
  capacity?: number;
  maxPalletCapacity?: number;
  maxWeightKg?: number;
  maxVolumeCm3?: number;
  maxLpnCount?: number;
}

export interface BulkCreateRacksRequest {
  warehouseId: string;
  area: string;
  rowsToAdd?: number;
  baysPerRow?: number;
  levelsPerRack?: number;
  binsPerLevel?: number;
  startRow?: number;
  startBay?: number;
}

export interface BulkCreateRacksResponse {
  message: string;
  area: string;
  createdRacks: number;
  createdLocations: number;
  skippedRacks: string[];
}

export interface RackDeleteResponse {
  message: string;
  area: string;
  rowNumber: string;
  bayNumber: string;
  deletedLocations: number;
}

export interface LocationHierarchy {
  warehouseId: string;
  hierarchy: {
    [area: string]: {
      [row: string]: {
        [bay: string]: Location[];
      };
    };
  };
}

export const locationsApi = {
  getAll: async (): Promise<Location[]> => {
    return apiClient.get<Location[]>('/master/locations');
  },

  getById: async (id: string): Promise<Location> => {
    return apiClient.get<Location>(`/master/locations/${id}`);
  },

  getByCode: async (locationCode: string): Promise<Location> => {
    return apiClient.get<Location>(`/master/locations/code/${locationCode}`);
  },

  getByWarehouse: async (warehouseId: string): Promise<Location[]> => {
    return apiClient.get<Location[]>(`/master/locations/warehouse/${warehouseId}`);
  },

  /**
   * Get only storage locations (exclude staging, receiving, shipment, packing areas)
   * For warehouse map visualization - only show racks, not staging areas
   */
  getStorageLocationsByWarehouse: async (warehouseId: string): Promise<Location[]> => {
    return apiClient.get<Location[]>(`/master/locations/warehouse/${warehouseId}/storage-only`);
  },

  getRackOccupancy: async (warehouseId: string): Promise<BinOccupancy[]> => {
    return apiClient.get<BinOccupancy[]>(`/master/locations/warehouse/${warehouseId}/rack-occupancy`);
  },

  getRackSummaries: async (
    warehouseId: string,
    options?: { limit?: number; offset?: number }
  ): Promise<RackSummary[]> => {
    const params = new URLSearchParams();
    if (options?.limit != null) params.set("limit", String(options.limit));
    if (options?.offset != null) params.set("offset", String(options.offset));
    const query = params.toString();
    return apiClient.get<RackSummary[]>(
      `/master/locations/warehouse/${warehouseId}/rack-summaries${query ? `?${query}` : ""}`
    );
  },

  getOperationalStations: async (warehouseId: string): Promise<OperationalStation[]> => {
    return apiClient.get<OperationalStation[]>(
      `/master/locations/warehouse/${warehouseId}/operational-stations`
    );
  },

  getRackDetail: async (warehouseId: string, rackId: string): Promise<BinOccupancy[]> => {
    const params = new URLSearchParams({ rackId });
    return apiClient.get<BinOccupancy[]>(`/master/locations/warehouse/${warehouseId}/rack-detail?${params.toString()}`);
  },

  getIntegritySummary: async (warehouseId: string): Promise<IntegritySummary> => {
    return apiClient.get<IntegritySummary>(`/master/locations/warehouse/${warehouseId}/integrity-summary`);
  },

  createPlacementPlan: async (body: {
    warehouseId: string;
    materialId: string;
    totalQuantity: number;
    preferredLocationCode?: string;
    excludeLocationCodes?: string[];
  }): Promise<PlacementPlan> => {
    return apiClient.post<PlacementPlan>("/master/locations/placement-plan", body);
  },

  getHierarchyByWarehouse: async (warehouseId: string): Promise<LocationHierarchy> => {
    // Backend returns { warehouseId, hierarchy } but we need to transform it
    const response = await apiClient.get<{ warehouseId: string; hierarchy: any }>(`/master/locations/hierarchy?warehouseId=${warehouseId}`);
    return {
      warehouseId: response.warehouseId,
      hierarchy: response.hierarchy,
    };
  },
  
  getHierarchy: async (warehouseId: string): Promise<LocationHierarchy> => {
    // Alias for getHierarchyByWarehouse
    return locationsApi.getHierarchyByWarehouse(warehouseId);
  },

  create: async (location: CreateLocationRequest): Promise<Location> => {
    return apiClient.post<Location>('/master/locations', location);
  },

  update: async (id: string, location: UpdateLocationRequest): Promise<Location> => {
    return apiClient.put<Location>(`/master/locations/${id}`, location);
  },

  delete: async (id: string): Promise<void> => {
    return apiClient.delete<void>(`/master/locations/${id}`);
  },

  // Rack-specific endpoints
  updateRack: async (id: string, updates: UpdateRackRequest): Promise<Location> => {
    return apiClient.put<Location>(`/master/locations/racks/${id}`, updates);
  },

  bulkCreateRacks: async (request: BulkCreateRacksRequest): Promise<BulkCreateRacksResponse> => {
    return apiClient.post<BulkCreateRacksResponse>('/master/locations/bulk-racks', request);
  },

  deleteRack: async (
    warehouseId: string,
    area: string,
    rowNumber: string,
    bayNumber: string
  ): Promise<RackDeleteResponse> => {
    const params = new URLSearchParams({
      warehouseId,
      area,
      rowNumber,
      bayNumber,
    });
    return apiClient.delete<RackDeleteResponse>(`/master/locations/racks?${params.toString()}`);
  },
};
